name: world_radio_app
description: A global radio streaming app featuring live stations and customizable themes.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  cupertino_icons: ^1.0.6
  http: ^0.13.5
  audioplayers: ^1.0.1
  provider: ^6.1.1
  url_launcher: ^6.2.5

  # For theme customization
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/